baseurl: https://blog.heimsbakk.net/
languageCode: en
title: "> /dev/null 2>&1"
theme: mini
hasCJKLanguage: false
summaryLength: 50

# googleAnalytics: "your_google_analytics_id"
# disqusShortname: "blogheimsbakknet"

taxonomies:
  category: categories
  tag: tags

# About syntax highlighting: https://gohugo.io/content-management/syntax-highlighting/
# Style galary: https://xyproto.github.io/splash/docs/all.html
# hugo gen chromastyles --style= > syntax.css

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4

social:
  twitter: https://twitter.com/aheimsbakk
  github: https://github.com/aheimsbakk
  linkedin: https://www.linkedin.com/in/arnulfheimsbakk

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: false
    disable: true
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: true
    enableDNT: false
    simple: false
  vimeo:
    disable: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

params:
  author: Arnulf Heimsbakk
  description: This blog is mostly updated with stuff I don't want to forget. The content is configuration snippets or links for use at home.
  bio: ramblings of a sysadmin

  enableRSS: true
  enableComments: false
  enableGoogleAnalytics: false
  showToc: false
  showPowerBy: true
  math: false
  hiddenPostSummaryInHomePage: false
  # copyright: ''

  customCSS:
    - css/overrides.css
  customJS: []

  # Extra links in navigation
  links:
    ## e.g.
    # - name: Project
    #   path: /project
