baseurl: https://blog.heimsbakk.net/
languageCode: en
title: "> /dev/null 2>&1"
theme: cactus-plus
#googleAnalytics: "your_google_analytics_id"
hasCJKLanguage: false

taxonomies:
  category: categories
  tag: tags

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: autumn
    tabWidth: 4

social:
  twitter-square: https://twitter.com/aheimsbakk
  github-square: https://github.com/aheimsbakk
  linkedin-square: https://www.linkedin.com/in/arnulfheimsbakk

privacy:
  disqus:
    disable: true
  googleAnalytics:

    anonymizeIP: false
    disable: true
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: true
    enableDNT: false
    simple: false
  vimeo:
    disable: true
    simple: false
  youtube:
    disable: true
    privacyEnhanced: false

params:
  author: Arnulf Heimsbakk
  description: Sysadmin that blogs when life get boring
  bio: ramblings of a sysadmin

  twitter: ""
  facebook: ""

  enableRSS: true
  enableToc: false

  enableDisqus: false
  disqusShortname: "blogheimsbakknet"

  enableSummary: true
  # Set the value to true if use description in post front matter replace content summary
  useDescriptionReplaceSummary: false

  enableGoogleAnalytics: false
  enableBaiduAnalytics: false
  # Set the value to your baidu analysis code if you want to use baidu analytics
  baiduAnalytics: 'your_baidu_analysis_code'

  enableTwitterCard: false
  # The url for twitter card image, default is avatar.png in static/images directory
  twitterCardImage: ""

  # Add custom assets with their paths relative to the static folder
  customCSS:
    - css/code-size.css
    - css/width.css
    - css/syntax.css
  customJS: []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home: ""
  about: ""
  archive: ""
  subscribe: ""

  olderPosts: ""
  newerPosts: ""
  copyright: ""

  # show latest posts in single page
  showLatestPosts: false
  readMore: ""

  # Share
  enableShare: false
  tweet: " "
  share: " "

  # 404 page
  title404: ""
  subtitle404: ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont: "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle: ""

